### ISSUE TITLE
MCP License Violation

### ISSUE THREAD

**Issue by half-cambodian-hacker-man** [phase/MinecraftMappings#1]
Hello there. I'm writing to inform you that this project is under violation of MCP's license.

As stated:
> You are NOT allowed to:
> - Use any of MCPs scripts, tools or data files without explicit written permission.

Without express written permission, you are legally obstructed from using the project at all. Sorry m9

**Comment by Jordin** [comment]
I was under the impression that MCP was licensed using the GNU GPL v2 license. I believe this to be the case, since MCP is shipped with Retroguard, and Retroguard is licensed using the GNU GPL v2.

**Comment by LexManos** [comment]
It is not, there is a full list of licenses in the packages you download.

**Comment by phase** [comment]
They're no longer in the repo
